// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionAttemptDto } from "./ExecutionAttemptDto";
import type { ExecutionFindingDto } from "./ExecutionFindingDto";
import type { ExecutionLogDto } from "./ExecutionLogDto";
import type { ExecutionPhaseEventDto } from "./ExecutionPhaseEventDto";
import type { ExecutionRunDto } from "./ExecutionRunDto";

export type ExecutionDetailDto = { run: ExecutionRunDto, attempts: Array<ExecutionAttemptDto>, recentLogs: Array<ExecutionLogDto>, findings: Array<ExecutionFindingDto>, recentEvents: Array<ExecutionPhaseEventDto>, blockingFindingCount: number, canResume: boolean, canCancel: boolean, deliveryReady: boolean, };
