// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionLogDto = { id: string, commandId: string, phase: string, program: string, stream: string, sequence: number, text: string, truncated: boolean, createdAt: string, };
