// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionAttemptDto = { id: string, number: number, reason: string, status: string, errorCode: string | null, errorMessage: string | null, startedAt: string, completedAt: string | null, };
