// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionFindingDto = { id: string, externalId: string, severity: string, title: string, body: string, path: string | null, line: number | null, status: string, dispositionNote: string | null, firstSeenIteration: number, lastSeenIteration: number, createdAt: string, updatedAt: string, resolvedAt: string | null, };
