// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntakeGithubIssueRequest = { repositoryId: string, reference: string, requirePlanApproval: boolean, };
