// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanRevisionDto } from "./PlanRevisionDto";
import type { PlanningAgentDto } from "./PlanningAgentDto";
import type { PlanningEventDto } from "./PlanningEventDto";
import type { PlanningQuestionDto } from "./PlanningQuestionDto";
import type { PlanningQueueDto } from "./PlanningQueueDto";
import type { PlanningRunDto } from "./PlanningRunDto";
import type { PlanningSourceDto } from "./PlanningSourceDto";
import type { TerminalHandoffSummaryDto } from "./TerminalHandoffSummaryDto";

export type PlanningDetailDto = { source: PlanningSourceDto, currentPhase: string, status: string, run: PlanningRunDto, agents: Array<PlanningAgentDto>, pendingQuestions: Array<PlanningQuestionDto>, answeredQuestions: Array<PlanningQuestionDto>, plan: PlanRevisionDto | null, queue: PlanningQueueDto, recentEvents: Array<PlanningEventDto>, terminalHandoff: TerminalHandoffSummaryDto | null, };
