// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanningRunDto = { id: string, workItemId: string, status: string, errorCode: string | null, errorMessage: string | null, idempotencyKey: string | null, createdAt: string, updatedAt: string, completedAt: string | null, };
