// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanRevisionDto = { id: string, revision: number, editRevision: number, markdownBody: string, approvalPolicy: string, approvalStatus: string, createdAt: string, updatedAt: string, };
