// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanningEventDto = { id: string, planningAgentId: string, attempt: number, sequence: number, eventKind: string | null, payload: unknown, createdAt: string, };
