// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanningSourceDto = { workItemId: string, repositoryId: string, title: string, kind: string, reference: string | null, markdownBody: string, };
