// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanningAgentDto = { id: string, role: string, ordinal: number, modelId: string, sessionName: string, status: string, attempt: number, errorCode: string | null, errorMessage: string | null, createdAt: string, updatedAt: string, completedAt: string | null, };
