// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueEntryDto } from "./QueueEntryDto";

export type PlanningQueueDto = { state: string, eligible: boolean, reason: string | null, entry: QueueEntryDto | null, };
