// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanningQuestionDto = { id: string, planningAgentId: string, externalId: string, ordinal: number, promptMarkdown: string, status: string, answerMarkdown: string | null, createdAt: string, updatedAt: string, };
