// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueueEntryDto = { id: string, position: number, schedulingStatus: string, createdAt: string, updatedAt: string, };
