// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepositoryDto = { id: string, rootPath: string, displayName: string, createdAt: string, updatedAt: string, };
