// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolveExecutionFindingRequest = { runId: string, findingId: string, dispositionNote: string, };
