// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalHandoffSummaryDto = { id: string, planningAgentId: string, sessionName: string, status: string, manualReconcileAvailable: boolean, errorCode: string | null, errorMessage: string | null, createdAt: string, updatedAt: string, };
