// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateSettingsRequest = { planningModels: Array<string>, implementationModel: string, adversaryModel: string, terminalApplication: string, terminalArguments: string, };
