// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkItemDto = { id: string, repositoryId: string, title: string, sourceKind: string, markdownBody: string, lifecycleStatus: string, requirePlanApproval: boolean, createdAt: string, updatedAt: string, };
